name: Create Release

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Create version
        id: version
        run: |
          DATE_TIME=$(date '+%Y.%m.%d.%H.%M')
          SHA8=$(git rev-parse --short HEAD)
          echo "VERSION=${DATE_TIME}-${SHA8}" >> "${GITHUB_OUTPUT}"

      - name: Generate Release Notes
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.version.outputs.VERSION }}
        run: gh release create "${VERSION}" --target "${GITHUB_REF_NAME}" --generate-notes